server:
  port: 5000

spring:
  application:
    name: api-gateway
#    admin:
#          jmx-name: org.springframework.boot:type=Admin,name=SpringApplicationZuul

  cloud:
    zookeeper:
      connect-string: localhost:2181
      discovery:
        register: true
        root: dev
  http:
    multipart:
      max-file-size: 5MB

zuul:
  ignored-patterns: /**/feign/**

ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 20000
  maxAutoRetries: 0



#    api:
#      path: /api/**
#      url: http://localhost:8080
#    api-a:
#      path: /api-a/**
#      serviceId: hello-service
#    api-b:
#      path: /api-b/**
#      serviceId: feign-consumer
#    hello-service: /api-a/**
#    feign-consumer: /api-b/**

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
