#server:
#  context-path: /demo

spring:
  application:
   name: hello-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/gray?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /static

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#    region: hz
#    use-dns-for-fetching-service-urls: true
#    eureka-server-d-n-s-name: simple.com
#    eureka-server-u-r-l-context: eureka
#    eureka-server-port: 8761
#    prefer-same-zone-eureka: true


#management:
#  security:
#    enabled: false

mybatis:
  type-aliases-package: com.simple.demo.model
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl


